import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Nav from "./_components/Nav";
import Provider from "./_components/Provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Nav />
          <div className="mt-32">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
